# -*- coding: utf-8 -*-
"""Keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwoyaWkdAD5BhMBGBfECHa3HZGAVGkuI

Seguindo este [tutorial](https://www.youtube.com/watch?v=V9mWsCILn7c&index=8&list=PL39zyvnHdXh8dWhFchbnhaQW617-LT5F-&ab_channel=C%C3%B3digoLogo-Programa%C3%A7%C3%A3oeIntelig%C3%AAnciaArtificial)
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense

'''
      Horas    Estudou -> Nota
          8       3          7
          10      4          8
          5       7          9.5
          5       7          4.5
          5       10         5
          10      6          10

'''

x = np.array([[0.8, 0.3], [1.0, 0.4], [1.0, 0.5],[5.0, 7.0],[5.0, 1.0],[1.0, 6.0]])
y = np.array([[0.7],[0.8], [0.95],[0.45],[0.5],[1.0]])

model = Sequential() #modelo 1-3 - 1

model.add(Dense(5, input_dim=2)) #criou o modelo
model.add(Dense(1))
# sgd = gradiente descendente estocástico
# erro = erro mínimo quadrado
model.compile(optimizer='sgd', loss='mse', metrics=['acc'])

#treinando o modelo
#epochs = tentativas de aprendizado
model.fit(x, y, epochs=1000)

while True:
  dormiu = input('Dormiu: ')
  estudou = input('Estudou: ')
  
  lista = [float(dormiu), float(estudou)]
  
  
  t = np.asmatrix(lista)
  
  result = model.predict(t)
  
  print(' previsto => ', str(result[0][0]* 10.0), ' como nota.')